//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnEF.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class Product
    {
        public int ProductId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> Detail { get; set; }

        [JsonIgnore]
        public virtual Detailproduct Detailproduct { get; set; }
    }
}
